<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UnsuccessfullRegister</name>
   <tag></tag>
   <elementGuidId>fc1473b6-542e-40bb-ab4c-901cbc028881</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/main/div/div/div/div[2]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/main/div/div/div/div[2]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
