<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ReduceItem</name>
   <tag></tag>
   <elementGuidId>3828fdf6-1d23-4572-9026-1ee28c364514</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/main/div/div/div[1]/div/div[1]/div[2]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/main/div/div/div[1]/div/div[1]/div[2]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
