<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonDetailAPI</name>
   <tag></tag>
   <elementGuidId>ab9e614b-c6ce-4c5a-9448-5350d7b63d7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/main/div/div/div[2]/div/div[14]/div/div[3]/div[2]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/main/div/div/div[2]/div/div[14]/div/div[3]/div[2]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
