<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DragDown</name>
   <tag></tag>
   <elementGuidId>83a3f49b-a4df-4a78-bc2b-b35a55e9ac39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[1]/main/div/div/div[1]/div/div[1]/div[1]/div[3]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[1]/main/div/div/div[1]/div/div[1]/div[1]/div[3]/div/i</value>
   </webElementProperties>
</WebElementEntity>
