<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubTotal</name>
   <tag></tag>
   <elementGuidId>77a557dc-52ee-4a77-b0ec-e8809d11893f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[1]/main/div/div/div/div/div[1]/table/thead/tr/th[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[1]/main/div/div/div/div/div[1]/table/thead/tr/th[4]</value>
   </webElementProperties>
</WebElementEntity>
