<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PayKambing</name>
   <tag></tag>
   <elementGuidId>2f6b83e8-9a3a-44f8-a167-77cdc81d0834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/main/div/div/div[2]/div/div[10]/div/div[3]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/main/div/div/div[2]/div/div[10]/div/div[3]/div[2]/button</value>
   </webElementProperties>
</WebElementEntity>
